### ISSUE TITLE
[Bug] No validation css for <el-select> component

### ISSUE THREAD

**Issue by BurwandSwordfish** [creativetimofficial/ct-vue-black-dashboard-pro#34]
### Version
1.2.3
### Reproduction link
https://jsfiddle.net/fzxmvh5d/
### Operating System
11.2.3
### Device
Mac
### Browser & Version
Chrome
### Steps to reproduce
1. Just create a Validation from with a <el-select> component
### What is expected?
Needs to function the same as the <base-input> component.
### What is actually happening?
The select does not change when the validation is false.

---

**Comment by rarestoma** [comment]
Hi @BurwandSwordfish,

Thank you for working with our products.

I did some tests now and I found a solution that works on my side.

Go to `src/pages/Forms/ValidationForms/LoginForm.vue` and add the following:

```
<ValidationProvider
          name="country"
          rules="required|min:3"
          v-slot="{ passed, failed, errors }"
        >
        <base-input required :error="errors[0]" :class="[{ 'has-success': passed }, { 'has-danger': failed }]">
          <el-select
            v-model="country"
            class="select-primary"
            name="country"
          >
            <el-option
              v-for="country in countryOptions"
              class="select-primary"
              :label="country"
              :value="country"
              :key="country"
            ></el-option>
          </el-select>
         </base-input>
       </ValidationProvider>
```

On the script section import the select and option from element-ui and add the country and countryOptions data:

<script>
import { extend } from "vee-validate";
import { required, email, min } from "vee-validate/dist/rules";
import { configure } from 'vee-validate';
**import { Select, Option } from 'element-ui';**

extend("email", email);
extend("required", required);
extend("min", min);

export default {
  **components: {
    [Select.name]: Select,
    [Option.name]: Option
  },**
  data() {
    return {
      email: "",
      password: "",
      fullname: "",
      **country: '',
      countryOptions: [
        'Australia',
        'Germany',
        'Netherlands',
        'USA',
        'UK',
        'New Zealand'
      ]**
    };
  },
  methods: {
    submit() {
      alert("Form has been submitted!");
    }
  }
};
</script>

Please let me know if it works.

Best regards,
Rares

**Comment by BurwandSwordfish** [comment]
@rarestoma - I did the changes but it still does not seem to work.
![image](https://user-images.githubusercontent.com/82020992/121333435-19d9c680-c919-11eb-84f1-fc6a0dccfb94.png)

**Comment by BurwandSwordfish** [comment]
@rarestoma - I did find a why to fix it by adding this to the _forms.scss, I am just not sure how to move the x to the left
```css

.has-success .form-control:focus,
.has-danger .el-input__inner,
.has-success.input-group-focus .input-group-append .input-group-text,
.has-success.input-group-focus .input-group-prepend .input-group-text{
  border-color: darken($success, 10%) !important;
}

.has-danger .form-control,
.has-danger .el-input__inner,
.has-danger .input-group-append .input-group-text,
.has-danger .input-group-prepend .input-group-text,
.has-danger.input-group-focus .input-group-prepend .input-group-text,
.has-danger.input-group-focus .input-group-append .input-group-text{
    border-color: lighten($danger-states,5%) !important;
    color: $danger-states;
    background-color: rgba(222,222,222, .1) !important;;

    &:focus{
        background-color: $transparent-bg;
    }
}
```
![image](https://user-images.githubusercontent.com/82020992/121334484-fc592c80-c919-11eb-9fa0-17c80d9afc78.png)
